Virus-Axel/godot-solana-sdk

src/keypair.cpp
src/pubkey.cpp
src/solana_sdk.cpp
wrapper/src/modules/keypair.rs
wrapper/src/modules/pubkey.rs
wrapper/wrapper.h

Fix getters of key values and bytes

---

src/solana_client.cpp

On web browsers, the SolanaClient does not work. This commits fixes this bug by using XMLHTTPRequest javascript class. A depricated feature is used to have synchronous calls. This is necessary to keep SolanaClient static.

Fix solana client for web target

---

include/solana_client.hpp
src/solana_client.cpp

The SolanaClient was not working when setting port or query strings. This commit implements a better url parsing by considering all URL options.

Implement URL parsing

---

include/anchor_program.hpp
include/pubkey.hpp
src/anchor_program.cpp
src/pubkey.cpp
src/register_types.cpp
src/solana_client.cpp

Anchor Programs is required, this commit adds an implementation of an AnchorProgram Node. The node interface an Anchor program wit two methods. One for calling instructions and one for fetching accounts.

Add AnchorProgram interface

---

.github/workflows/build.yml
SConstruct

- [x ] The commit(s) are rebased and squashed
- [ x] Commits are concise and does not contain several different changes.

Add web and IOS target to workflow build

---

.github/workflows/run_examples.yml
example/Pubkeys/PubkeysExample.gd
example/Transactions/transaction_example.gd
godot-solana-sdk.gdextension

There are no way to know if changes are breaking functionality. This makes maintainence crucial for new bugs on new commits. Automatic tests are added to avoid this by creating a github action that runs all example projects in the example directory. In this commit thex are also modified to exit on failure for github to distinguish failed from passed tests.

Add automatic tests

---

example/SolanaClient/SolanaClientExamples.gd
example/SolanaClient/solana_client_examples.tscn
src/solana_client.cpp

The subscribe methods were not tested. This commit adds tests and also includes small adjustments to the ws url to make it work properly.

Add client subscribe tests

---

example/SolanaClient/SolanaClientExamples.gd
example/SolanaClient/solana_client_examples.tscn
include/solana_client.hpp
instructions/src/mpl_candy_machine.cpp
instructions/src/mpl_token_metadata.cpp
src/anchor_program.cpp
src/solana_client.cpp
src/transaction.cpp

The synchronous client calls did not work. Fix the client calls to work when the node is not inside tree. A test case for synchronous calls is also added.

Fix synchronous client calls

---

.github/workflows/build.yml

Include .gdext file in artifact

---

.github/workflows/puppeteer/puppeteer.js
.github/workflows/run_examples.yml
example/WalletAdapterWeb/WalletAdapterDemo.gd

The backpack build fails and needs to be replaced. Backpack is replaced with a solana wallet mock. This also enables testing of different wallets in godot projects.

Replace backpack with solana-wallet-mock in workflows

---

src/anchor_program.cpp

The fetch account method returns an empty dictionary on error. It is hard to fault trace when encountering. Error messages are added to solve this.

Add error messages to fetch anchor account

---

README.md

typo : pugin to plugin

---

example/Keypair/KeypairDemo.gd
include/keypair.hpp
src/keypair.cpp

Add keypair to pubkey conversion method

---

src/message.cpp
src/transaction.cpp

Add error message for not enough signers

---

include/keypair.hpp

Add doxygen comments to Keypair Class and methods

---

include/pubkey.hpp
src/pubkey.cpp

Add parameter check on pda creation methods

---

include/transaction/message.hpp
src/transaction/message.cpp
wallet_adapter/wallet_adapter.hpp

Solflare has a check that modifies the unit price if it is too low. To get around that, an adjustment is added to use the minimum price if lower than the limit.

Add minimum unit price adjustment for solflare

---

.clang-format
.clang-tidy
SConstruct

Add clang tidy and format

---

example/Tokens/project.godot
include/solana_client/solana_client.hpp
include/solana_utils.hpp
include/transaction/transaction.hpp
include/wallet_adapter/wallet_adapter.hpp
src/solana_client/solana_client.cpp
src/transaction/transaction.cpp
src/wallet_adapter/wallet_adapter.cpp

Fix clang tidy warnings in transaction files

---

.github/workflows/deploy_docs.yml

Fix doxygen deployment removing benchmark data

---

include/transaction/merged_account_metas.hpp
include/transaction/message.hpp
include/transaction/transaction.hpp
src/transaction/merged_account_metas.cpp
src/transaction/message.cpp
src/transaction/transaction.cpp

Add docs and fix clang-tidy warnings in message

---

.github/workflows/build.yml
.github/workflows/puppeteer/puppeteer.js
example/WalletAdapterWeb/WalletAdapterWeb.tscn
godot-solana-sdk.gdextension
src/anchor_program.cpp

Fix Anchor crash with optional accounts

---

include/transaction/transaction.hpp
src/transaction/transaction.cpp

Revert solflare priority fee correction

---

src/transaction/transaction.cpp

Fix compute budget not updating message

---

.clang-tidy
include/candy_machine/candy_guard_access_list.hpp
include/solana_client/rpc_multi_http_request_client.hpp
include/solana_client/rpc_single_ws_request_client.hpp
include/solana_client/solana_client.hpp
include/solana_utils.hpp
include/transaction/address_lookup_table.hpp
src/candy_machine/candy_guard.cpp
src/candy_machine/candy_guard_access_list.cpp
src/solana_client/rpc_multi_http_request_client.cpp
src/solana_client/rpc_single_ws_request_client.cpp
src/solana_client/solana_client.cpp
src/solana_utils.cpp
src/transaction/address_lookup_table.cpp
src/transaction/merged_account_metas.cpp
src/wallet_adapter/wallet_adapter.cpp

Fix clang warnings in SolanaClient

---

include/solana_client/rpc_single_http_request_client.hpp
include/solana_client/rpc_single_ws_request_client.hpp
include/solana_utils.hpp
src/solana_client/rpc_single_http_request_client.cpp
src/solana_client/rpc_single_ws_request_client.cpp

Fix clang warnings in WS client

---

include/solana_client/rpc_single_http_request_client.hpp
include/solana_client/rpc_single_ws_request_client.hpp
src/solana_client/rpc_single_http_request_client.cpp

Fix clang warnings in HTTP single client

---

include/solana_client/rpc_multi_http_request_client.hpp
include/solana_client/rpc_single_http_request_client.hpp
src/solana_client/rpc_multi_http_request_client.cpp
src/solana_client/rpc_single_http_request_client.cpp

Fix clang warnings in multi HTTP client

---

include/solana_client/solana_client.hpp
src/register_types.cpp

Fix clang-tidy warnings in register_types.cpp

---

wallet_adapter_bridge/src/bindings.js

Fix clear state removing transaction

---

.github/workflows/simple_benchmark.yml
measurements/simplebenchmark/TransactionMeasure.tscn
measurements/simplebenchmark/project.godot
measurements/simplebenchmark/transaction_measure.gd.uid

Update godot version in benchmark job

---

include/solana_client/solana_client.hpp
src/solana_client/solana_client.cpp

The key parameters of SolanaClient only accepts Strings. The parameter types are changed to accept a variant instead. The Variants are converted to Strings.

Fix account key parameters in SolanaClient

---

example/Transactions/transaction_example.gd
example/Transactions/transaction_example.tscn
src/pubkey.cpp
src/transaction/transaction.cpp

Enable JSON quick select for payer property

---

.github/workflows/build.yml

Add package plugin

---

.github/workflows/run_examples.yml

Change trigger of running examples

---

.github/workflows/run_examples.yml

Use artifact instead of building

---

.github/workflows/build.yml
.github/workflows/run_examples.yml

Add reusable workflow for tests

---

.github/workflows/build.yml
.github/workflows/run_examples.yml

Revert run example workflow but optimized

---

.github/workflows/run_examples.yml
example/SolanaClient/SolanaClientExamples.gd
example/SolanaClient/SolanaClientExamples.gd.uid
example/SolanaClient/project.godot
example/SolanaClient/solana_client_examples.tscn
example/SolanaClient/test_accounts/HFWX8c7kpa7Lq496ccesyDrRcY27MhsvtK3DsBoAQhvk.json
example/SolanaClient/test_accounts/dev2gUnXyMLh6WyV9NTBaXeNfo1DTn2R4b69VTGNidF.json
include/solana_client/solana_client.hpp
src/solana_client/solana_client.cpp

Add option to get fungible tokens in get_asset_by_owner

---

docs/xml_to_header.py

The documentation does not show in Godot editor. This commit fixes the problem by aligning a search pattern with a doxygen alias for Godot visible functions.

Fix doxygen to editor doc issue

---

addons/SolanaSDK/solana_sdk_plugin.gd
android/plugin/src/main/java/plugin/walletadapterandroid/GDExtensionAndroidPlugin.kt
android/plugin/src/main/java/plugin/walletadapterandroid/MyComposable.kt
include/wallet_adapter/wallet_adapter.hpp
src/wallet_adapter/wallet_adapter.cpp

Fix missing dependency issue

---

include/solana_utils.hpp
src/anchor/anchor_program.cpp
src/solana_utils.cpp

Adjust error handling for null result

---

include/solana_client/rpc_single_http_request_client.hpp
src/solana_client/rpc_single_http_request_client.cpp

Fix bug causing crash on timeouts

---

android/plugin/src/main/java/plugin/walletadapterandroid/GDExtensionAndroidPlugin.kt
android/plugin/src/main/java/plugin/walletadapterandroid/MyComposable.kt
include/wallet_adapter/wallet_adapter.hpp
src/wallet_adapter/wallet_adapter.cpp

Add properties for MWA identity

---

include/anchor/anchor_program.hpp
src/anchor/anchor_program.cpp
src/candy_machine/candy_machine.cpp

Add resyncing of JSON file in AnchorProgram Node

---

example/Transactions/transaction_example.gd
include/transaction/transaction.hpp
src/transaction/transaction.cpp

Add signal for transaction simulation failed

---

.github/workflows/asset_template.json.hb
.github/workflows/deploy_asset.yml
src/wallet_adapter/wallet_adapter.cpp

Add auto-deployment of addon package
