Virus-Axel/godot-solana-sdk

include/solana_sdk.hpp, include/transaction.hpp, include/utils.hpp, src/account_meta.cpp, src/keypair.cpp, src/solana_sdk.cpp, src/transaction.cpp, src/utils.cpp
Sending the transaction requires another solana-client plugin. This is not necessary since there is a HTTPClient class. This commit adds implementations for signing and sending transaction without the client plugin.
=> Add client features to send transaction

include/solana_client.hpp, src/register_types.cpp, src/solana_client.cpp, src/transaction.cpp
The underlying RPC client functions are necessary for future Node implementations. This commit add a static class to godot with all RPC functions.
=> Implement RPC client functions

include/message.hpp, include/transaction.hpp, src/message.cpp, src/transaction.cpp
The transaction method update_blockhash is broken. This commit introduces a temporary fix that uses an extra parameter to a account meta find algorithm. There are also some issues fixed with inverted logic.
=> Fix update blockhash function

godot-solana-sdk.gdextension
The .gdextension file is outdated and does not contain minimum required version. It also contains bad library paths. This commit resolves these problems.
=> Fix .gdextension file

include/transaction.hpp, src/transaction.cpp
There is no way to get any result from sent transactions. This commit adds a return value for the send method. The result from the SolanaClient is passed as return.
=> Add return value to transaction send

include/message.hpp, include/transaction.hpp, src/message.cpp, src/register_types.cpp, src/solana_client.cpp, src/transaction.cpp
The Compute budget instructions are prepended to transaction instruction array when phantom is signing. This commit adds the same instructions to get a valid signature from phantom. The instructions are to be replaced by system instruction with input parameters.
=> Add mandatory compute budget instructions to transactions.

SConstruct, include/account_meta.hpp, include/instruction.hpp, include/message.hpp, include/pubkey.hpp, include/transaction.hpp, instructions/include/compute_budget.hpp, instructions/src/compute_budget.cpp, src/account_meta.cpp, src/instruction.cpp, src/message.cpp, src/pubkey.cpp, src/register_types.cpp, src/transaction.cpp
The prepended compute budget instructions cause issues. There are some serialization issues and they are prepended once the editor is restarted. This commit fixes this by removing reduntant code and refactoring message creation and instruction compilation.
=> Fix ComputeBudget bug

instructions/include/spl_token.hpp, instructions/src/spl_token.cpp, src/register_types.cpp
Tokens cannot be created easily. This commit introduces a TokenProgram node. This node has a instruction set for creating single signature tokens.
=> Implement token program node

include/instruction.hpp, include/keypair.hpp, include/pubkey.hpp, instructions/src/system_program.cpp, src/instruction.cpp, src/keypair.cpp, src/pubkey.cpp, src/transaction.cpp
The creat program address methods are inaccessible from GDScript. This binds static Pubkey methods to create various kinds of keys. It also introduces other convinient create methods to the GDScript interface.
=> Bind GDScript to program address creation

instructions/include/associated_token_account.hpp, instructions/src/associated_token_account.cpp, src/register_types.cpp
There is no way to actually create the associated token accounts on chain. This commit adds the node to build the instruction for that.
=> Add AssociatedTokenAccountProgram node

include/meta_data.hpp, include/pubkey.hpp, instructions/src/mpl_token_metadata.cpp, src/meta_data.cpp, src/pubkey.cpp, src/register_types.cpp
The metadata parsed from account data does not include creators or collections. This commit adds support by adding these properties to get_metadata method.
=> Parse creators and collections

include/solana_client.hpp, src/solana_client.cpp
The SolanaClient methods are needed to get notified instead of polling changes on the blockchain. This commit implements the subscribe methods needed to be able to make subscribe/unsubscribe requests to a RPC node. The subscribe methods take callables that are being executed on notifications from the RPC node.
=> Implement web socket methods for SolanaClient

example/SolanaClient/SolanaClientExamples.gd, example/SolanaClient/project.godot, example/Transactions/project.godot, example/Transactions/transaction_example.gd, example/Transactions/transaction_example.tscn, include/solana_client.hpp, include/transaction.hpp, instructions/include/mpl_token_metadata.hpp, instructions/src/mpl_token_metadata.cpp, src/register_types.cpp, src/solana_client.cpp, src/transaction.cpp
The URL must be set for all client instances and also transactions. This commit fixes this by adding a project setting for the URL. The other nodes have URL override properties instead to set individual URLs.
=> Add common SolanaClient URL

example/CandyMachine/candy_machine_data.tres, example/CandyMachine/candy_machine_demo.gd, example/CandyMachine/candy_machine_demo.tscn, example/CandyMachine/config_lines/1.tres, example/CandyMachine/meta_data.tres, include/transaction.hpp, instructions/include/mpl_candy_machine.hpp, instructions/include/spl_token.hpp, instructions/src/mpl_candy_machine.cpp, src/anchor_program.cpp, src/meta_data.cpp, src/register_types.cpp, src/transaction.cpp
The candy machine is incomplete and did not show how the candy machine could be used to mint from. This commit adds the sample code and also adds an instruction for config lines and a space calculation method.
=> Add mint to and config line sample code

example/SolanaClient/SolanaClientExamples.gd, include/solana_client.hpp, instructions/include/mpl_candy_machine.hpp, instructions/include/mpl_token_metadata.hpp, instructions/src/mpl_candy_machine.cpp, instructions/src/mpl_token_metadata.cpp, src/solana_client.cpp
The Nodes that inherit SolanaClient does not expose the properties. This commit modifies all nodes that has internal SolanaClient pointers to instead inherit the node. The SolanaClient node properties are thereby accessable to the user.
=> Add inheritance of SolanaClient node

.github/workflows/build.yml, .github/workflows/run_examples.yml
The build fails in newer version of scons. This commit locks the scons version to 4.2 for workflow jobs.
=> Fix build failing in new scons versions

example/SolanaClient/SolanaClientExamples.gd, example/SolanaClient/project.godot, include/solana_client.hpp, src/register_types.cpp, src/solana_client.cpp
The SolanaClient settings were not saving each time and caused annoying popups. This commit fixes this and also adds properties to enable specifying SolanaClient ports and port overrides.
=> Fix error with SolanaClient settings

example/SolanaClient/SolanaClientExamples.gd, include/anchor_program.hpp, src/anchor_program.cpp
The idl name seems to have updated some time ago. This commit adds support for new account data in the instructions. This makes the SDK able to determine if the account is signer and writable again.
=> Fix signer and writable in anchor instructions

include/anchor_program.hpp, instructions/src/associated_token_account.cpp, src/anchor_program.cpp
The token program parameter is not used in ATA builder. This commit fixes this and makes use of the supplied PID instead.
=> Fix token program parameter in ata builder

example/Transactions/transaction_example.gd, src/transaction.cpp
It was not possible to get blockhash before adding instructions. This can be desired in some situations. The prechecks were therefore removed from update_latest_blockhash method.
=> Remove instruction checks on update blockhash

example/Transactions/transaction_example.gd, src/instruction.cpp, src/instructions/mpl_candy_machine.cpp, src/message.cpp, src/transaction.cpp
When enabling some mint guards, the mint method crashes. This commit fixes the issue by allocating memory with memnew to comply with godot-cpp for godot 4.3.
=> Fix mint CandyGuard crash on some guards

include/meta_data/meta_data.hpp, src/meta_data/meta_data.cpp
Implement MetaData from_dict method. Copies elements from known paths into metadata properties. This is a useful method when fetching assets using DAS SolanaClient methods.
=> Implement a way to copy metadata from a dictionary

include/anchor_program.hpp, include/solana_client/solana_client.hpp, include/solana_utils.hpp, src/anchor_program.cpp, src/instruction.cpp, src/solana_client/solana_client.cpp, src/solana_utils.cpp
short_u16 fix on instruction
- [ x] The commit(s) are rebased and squashed
- [ 🥸] Commits are concise and does not contain several different changes.
Adds a way to fetch accounts with an rpc filter struct
get_program_accounts does not accept filters, so GPA cannot be used for e.g. memcmp filters
get_program_accounts optionally accepts filters, anchor programs can also now use this to create typed/positional filters. Later they can be named by stacking into an offsets dict, but for now they are 
* **Other …
=> memcmp filters and filters for anchor types

include/anchor_program.hpp, src/anchor_program.cpp
It adds support for the Optional accounts feature to the Anchor program client. #284 
Not implemented
Implemented
=> Added serializing optional accounts to instruction building

src/anchor_program.cpp
An additional commit didn't get pushed to optional accounts PR due to standard india issues. This adds those changes.
Optional accounts not working on most platforms and missing functionality
Works correctly with optional some and none.
=> adding missing commit to fix optional

include/transaction/transaction.hpp, src/transaction/transaction.cpp
The callback methods are bound to ClassDB to enable connecting them to signals. These methods are removed by connecting the callbacks with the callable_mp macro. The macro allows c++ methods to be connected.
=> Hide callback internal functions from Godot

example/SolanaClient/solana_client_examples.tscn, include/solana_client/rpc_multi_http_request_client.hpp, include/solana_client/rpc_single_http_request_client.hpp, include/solana_client/rpc_single_ws_request_client.hpp, include/solana_client/solana_client.hpp, src/solana_client/rpc_multi_http_request_client.cpp, src/solana_client/rpc_single_http_request_client.cpp, src/solana_client/rpc_single_ws_request_client.cpp, src/solana_client/solana_client.cpp
The SolanaClients were polling multiple times per frame. This also caused timeouts to speed up. This commit adds a check to only poll once per frame. It also somewhat fixes the timeout sync. It can still be inaccurate due to differences in the polling instance delta value.
=> Add check for polling multiple times per frame

.gitignore, SConstruct, docs/xml_to_header.py, include/hash.hpp, include/pubkey.hpp, src/pubkey.cpp, src/register_types.cpp
Currently there is no in editor documentation and users have no quick way to find information. This commit adds in editor documentation by extending the build script with another python script. This python script takes generated doxygen XML files and generates a header file. The class register code is extended to add the documentation in that header file.
=> Add in editor documentation from doxygen

wallet_adapter/solflare_js.hpp
Solflare signing was defined differently to make signing work. This workaround is not relevant anymore and causes a problem. This commit removes the previous workaround and causes the signing to pass.
=> Fix Solflare signing issue

example/WalletAdapterWeb/WalletAdapterDemo.gd, example/WalletAdapterWeb/WalletAdapterWeb.tscn, example/WalletAdapterWeb/project.godot, include/transaction/merged_account_metas.hpp, include/transaction/transaction.hpp, include/wallet_adapter/script_builder.hpp, include/wallet_adapter/wallet_adapter.hpp, src/transaction/merged_account_metas.cpp, src/transaction/message.cpp, src/transaction/transaction.cpp, src/wallet_adapter/wallet_adapter.cpp
Browser wallets fail whenever they alter the transactions. Since most wallets tend to modify the transactions more often, this commit introduces a way to adapt to the changes made by browser wallets. A method for detecting modifications is implemented. When modifications are detected, the transaction will be rebuilt from the browser wallet.
=> Fix signature verification failure for web wallets

example/Transactions/transaction_example.gd, include/pubkey.hpp, include/solana_utils.hpp, src/pubkey.cpp, src/transaction/merged_account_metas.cpp, src/transaction/transaction.cpp
The instruction compilation crashes if it gets strings as accounts. This commit adds support for non-object typed accounts by attempting to convert into a Pubkey first.
=> Fix support for string typed accounts internaly

example/WalletAdapterWeb/WalletAdapterDemo.gd, include/transaction/transaction.hpp, src/candy_machine/candy_guard.cpp, src/transaction/merged_account_metas.cpp, src/transaction/transaction.cpp
Wallet adapter signing was locked to use payer wallet adapter. This commit finds the signing wallet adapter by providing signer index to sign confirm callback.
=> Fix wallet adapter signing on deserialized transaction

example/Transactions/project.godot, example/Transactions/transaction_example.gd, example/Transactions/transaction_example.gd.uid, example/Transactions/transaction_example.tscn, include/solana_utils.hpp, include/transaction/transaction.hpp, src/register_types.cpp, src/transaction/transaction.cpp
When calling set_payer on a deserialized transaction, the signature state is cleared. This will also cause the transaction message to be recreated. This doesn't work since the data to create the message is unavailable. These changes adds a flag that indicates if the transaction is deserialized. If it is the set_payer method will warn user and do nothing.
=> Fix crash on set payer on deserialized transaction
